### PR TITLE
Initial draft of Anno factory w/ KBase support

### PR DESCRIPTION
**Pull request by devoid**
@cshenry 
I'm working on this since Ross requested that we get some models built for him soon. I'm wondering what the function:

ModelSEED::MS::Utilities::GlobalFunctions::functionToRoles does? I can see that in parses the role string but why are we storing compartment, delimiter, and comment? I worry because this compartment is just derived from the string annotation so it won't be consistent with (a) biochemistry compartments, (b) different annotation sources and (c) if the SEED decides to change the annotation "system".

Can I just pull the Contig > Feature > Role schema from the CDMI for Kbase? Do we need "compartment", "delimiter" and "comment" in the FeatureRole object?

### CODE REVIEW

**Comment by cshenry** [comment]
Woh woh. No. This is not how we are going to do this. At least, I don't
think so. I am coming back tomorrow. Let's discuss then. In general, before
you get sidetracked on this stuff, let me know... I at least want to have
discussions on the best way of doing things before ploying down a
particulary path.
On Jul 17, 2012 4:20 PM, "Scott Devoid" <
reply@reply.github.com>
wrote:

**Comment by cshenry** [comment]
Well, let me look it over. It could be okay. I would suggest we use the
kbase service that issues annotation typed objects.
Chris

**Comment by devoid** [comment]
@cshenry Is there an API that issues annotation typed objects? Or are you talking about an IRIS script? If there's an API call, I'd rather use that (fewer round-trips).

**Comment by cshenry** [comment]
There should be an API that issues the "Annotated genome" typed object that my "genome_to_fbamodel" command uses as input. Ask Bob about it. I'm virtually certain it exists. If it doesn't exist, one should be written.

Chris

**Comment by devoid** [comment]
@cshenry @pfrybar 
Ready to be merged.

**Pull request merged**
